# Generated by CodePress bootstrap-app-server.
# Edits are preserved, but running /codepress-bootstrap-app-server again may overwrite them.

FROM public.ecr.aws/docker/library/node:18-bookworm AS frontend-build

RUN corepack disable && npm install -g yarn@1.22.22

WORKDIR /app
COPY server /app/server
COPY web/package.json web/yarn.lock /app/web/
WORKDIR /app/web
RUN yarn install --frozen-lockfile --ignore-engines
COPY web/ /app/web/
RUN mkdir -p /app/server/static
RUN yarn build

FROM public.ecr.aws/docker/library/python:3.6-slim AS app

ENV PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1

WORKDIR /app/server

RUN pip install --no-cache-dir 'pip<22' 'setuptools<60' 'pipenv==2020.11.15'

COPY server/Pipfile server/Pipfile.lock /app/server/
RUN pipenv install --system --deploy

COPY server/ /app/server/
COPY --from=frontend-build /app/server/static/build /app/server/static/build
RUN python manage.py migrate --noinput
RUN chown -R 65534:65534 /app/server

EXPOSE 8000
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
