# Generated by CodePress bootstrap-app-server.
# Edits are preserved, but running /codepress-bootstrap-app-server again may overwrite them.

# ---- Stage 1: build the React frontend, then let its postbuild script copy
# the production build into server/static/build (this repo's Django app
# serves that directory directly, see server/server/server/settings.py) ----
FROM node:10 AS web-builder
WORKDIR /app
COPY server/ ./server/
COPY web/ ./web/
WORKDIR /app/web
RUN yarn install --frozen-lockfile
RUN mkdir -p /app/server/static
RUN yarn build

# ---- Stage 2: Django app server ----
FROM python:3.6-slim AS runtime
WORKDIR /app/server
COPY server/Pipfile server/Pipfile.lock ./
RUN pip install --no-cache-dir pipenv \
    && pipenv install --system --deploy --ignore-pipfile
COPY server/ ./
COPY --from=web-builder /app/server/static ./static
# The runtime sandbox executes the container as uid/gid 65534 (nobody), which
# needs write access to this directory so Django/SQLite can create db.sqlite3.
RUN chown -R 65534:65534 /app/server
EXPOSE 8000
CMD ["sh", "-c", "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"]
