# Generated by CodePress bootstrap-app-server.
# Edits are preserved, but running /codepress-bootstrap-app-server again may overwrite them.

FROM public.ecr.aws/docker/library/node:18-bookworm

RUN corepack enable && corepack prepare yarn@1.22.22 --activate

WORKDIR /app/web

COPY web/package.json web/yarn.lock ./
RUN yarn install --frozen-lockfile

COPY web ./

ENV HOST=0.0.0.0 \
    PORT=3000 \
    BROWSER=none \
    DANGEROUSLY_DISABLE_HOST_CHECK=true

EXPOSE 3000

CMD ["node", "node_modules/react-scripts/bin/react-scripts.js", "start"]
